language: rust
sudo: false

cache:
  cargo: true
  directories:
    - $HOME/.cache/bazel

rust: nightly

install:
  - export CC="gcc-4.8" CXX="g++-4.8"
  - source travis-ci/install.sh

script:
  - cargo test -vv -j 1 --features tensorflow_unstable
  - cargo run --example regression
  - cargo run --features tensorflow_unstable --example expressions
  - cargo doc -vv --features tensorflow_unstable
  - (cd tensorflow-sys && cargo test -vv -j 1)
  - (cd tensorflow-sys && cargo doc -vv)

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - g++-4.8
      - gcc-4.8
      - oracle-java8-installer
      - python-numpy
      - swig

notifications:
  email: false
